# frozen_string_literal: true

RSpec.describe AhlScraper::Games::Team do
  let(:raw_data) do
    # GAMEID: 1019976
    {
      "info": { "id": 390, "name": "Utica Comets", "city": "Utica", "nickname": "Comets", "abbreviation": "UTI", "logo": "https:\/\/assets.leaguestat.com\/ahl\/logos\/390.jpg", "divisionName": "North Division" },
      "stats": { "shots": 31, "goals": 4, "hits": 0, "powerPlayGoals": 1, "powerPlayOpportunities": 4, "goalCount": 4, "assistCount": 6, "penaltyMinuteCount": 12, "infractionCount": 6 },
    }
  end
  let(:opts) { { goals: goal_data, shots: shot_data, current_state: current_state, home_team: is_home_team, winning_team_id: 317 } }
  let(:goal_data) do
    [
      { game_goal_id: "103634", team: { id: 390, name: "Utica Comets", city: "Utica", nickname: "Comets", abbreviation: "UTI", logo: "https://assets.leaguestat.com/ahl/logos/390.jpg", divisionName: "North Division" }, period: { id: "1", shortName: "", longName: "1st" }, time: "16:00", scorerGoalNumber: "2", scoredBy: { id: 6901, firstName: "Guillaume", lastName: "Brisebois", jerseyNumber: 55, position: "D", birthDate: "" }, assists: [{ id: 4122, firstName: "Carter", lastName: "Camper", jerseyNumber: 19, position: "C", birthDate: "" }], assistNumbers: %w[11 0], properties: { isPowerPlay: "0", isShortHanded: "0", isEmptyNet: "0", isPenaltyShot: "0", isInsuranceGoal: "0", isGameWinningGoal: "0" }, plus_players: [{ id: 7101, firstName: "Kole", lastName: "Lind", jerseyNumber: 13, position: "RW", birthDate: "" }, { id: 4122, firstName: "Carter", lastName: "Camper", jerseyNumber: 19, position: "C", birthDate: "" }, { id: 7893, firstName: "Brogan", lastName: "Rafferty", jerseyNumber: 25, position: "D", birthDate: "" }, { id: 6901, firstName: "Guillaume", lastName: "Brisebois", jerseyNumber: 55, position: "D", birthDate: "" }, { id: 6080, firstName: "Justin", lastName: "Bailey", jerseyNumber: 95, position: "RW", birthDate: "" }], minus_players: [{ id: 5478, firstName: "Kyle", lastName: "Burroughs", jerseyNumber: 8, position: "D", birthDate: "" }, { id: 4186, firstName: "Ryan", lastName: "Bourque", jerseyNumber: 10, position: "LW", birthDate: "" }, { id: 6241, firstName: "Parker", lastName: "Wotherspoon", jerseyNumber: 27, position: "D", birthDate: "" }, { id: 7189, firstName: "Arnaud", lastName: "Durandeau", jerseyNumber: 29, position: "LW", birthDate: "" }, { id: 6748, firstName: "Jeff", lastName: "Kubiak", jerseyNumber: 36, position: "C", birthDate: "" }] },
      { game_goal_id: "103636", team: { id: 317, name: "Bridgeport Sound Tigers", city: "Bridgeport", nickname: "Sound Tigers", abbreviation: "BRI", logo: "https://assets.leaguestat.com/ahl/logos/317.jpg", divisionName: "Atlantic Division" }, period: { id: "1", shortName: "", longName: "1st" }, time: "18:28", scorerGoalNumber: "7", scoredBy: { id: 5834, firstName: "Matt", lastName: "Lorito", jerseyNumber: 14, position: "RW", birthDate: "" }, assists: [{ id: 2050, firstName: "Colin", lastName: "McDonald", jerseyNumber: 13, position: "RW", birthDate: "" }], assistNumbers: %w[6 0], properties: { isPowerPlay: "0", isShortHanded: "0", isEmptyNet: "0", isPenaltyShot: "0", isInsuranceGoal: "0", isGameWinningGoal: "0" }, plus_players: [{ id: 5478, firstName: "Kyle", lastName: "Burroughs", jerseyNumber: 8, position: "D", birthDate: "" }, { id: 2050, firstName: "Colin", lastName: "McDonald", jerseyNumber: 13, position: "RW", birthDate: "" }, { id: 5834, firstName: "Matt", lastName: "Lorito", jerseyNumber: 14, position: "RW", birthDate: "" }, { id: 7188, firstName: "Kieffer", lastName: "Bellows", jerseyNumber: 20, position: "LW", birthDate: "" }, { id: 6241, firstName: "Parker", lastName: "Wotherspoon", jerseyNumber: 27, position: "D", birthDate: "" }], minus_players: [{ id: 5929, firstName: "Ashton", lastName: "Sautner", jerseyNumber: 6, position: "D", birthDate: "" }, { id: 7082, firstName: "Lukas", lastName: "Jasek", jerseyNumber: 9, position: "RW", birthDate: "" }, { id: 7287, firstName: "Jonah", lastName: "Gadjovich", jerseyNumber: 21, position: "F", birthDate: "" }, { id: 6404, firstName: "Francis", lastName: "Perron", jerseyNumber: 27, position: "LW", birthDate: "" }, { id: 7416, firstName: "Olli", lastName: "Juolevi", jerseyNumber: 48, position: "D", birthDate: "" }] },
      { game_goal_id: "103641", team: { id: 317, name: "Bridgeport Sound Tigers", city: "Bridgeport", nickname: "Sound Tigers", abbreviation: "BRI", logo: "https://assets.leaguestat.com/ahl/logos/317.jpg", divisionName: "Atlantic Division" }, period: { id: "2", shortName: "", longName: "2nd" }, time: "2:52", scorerGoalNumber: "4", scoredBy: { id: 6830, firstName: "Nick", lastName: "Schilkey", jerseyNumber: 17, position: "RW", birthDate: "" }, assists: [{ id: 7646, firstName: "Mason", lastName: "Jobst", jerseyNumber: 25, position: "C", birthDate: "" }], assistNumbers: %w[3 0], properties: { isPowerPlay: "0", isShortHanded: "0", isEmptyNet: "0", isPenaltyShot: "0", isInsuranceGoal: "0", isGameWinningGoal: "0" }, plus_players: [{ id: 4889, firstName: "Seth", lastName: "Helgeson", jerseyNumber: 2, position: "D", birthDate: "" }, { id: 6830, firstName: "Nick", lastName: "Schilkey", jerseyNumber: 17, position: "RW", birthDate: "" }, { id: 7646, firstName: "Mason", lastName: "Jobst", jerseyNumber: 25, position: "C", birthDate: "" }, { id: 4696, firstName: "Tom", lastName: "Kuhnhackl", jerseyNumber: 41, position: "RW", birthDate: "" }, { id: 7198, firstName: "Bode", lastName: "Wilde", jerseyNumber: 46, position: "D", birthDate: "" }], minus_players: [{ id: 6834, firstName: "Stefan", lastName: "LeBlanc", jerseyNumber: 3, position: "D", birthDate: "" }, { id: 7101, firstName: "Kole", lastName: "Lind", jerseyNumber: 13, position: "RW", birthDate: "" }, { id: 7516, firstName: "Seamus", lastName: "Malone", jerseyNumber: 17, position: "F", birthDate: "" }, { id: 4122, firstName: "Carter", lastName: "Camper", jerseyNumber: 19, position: "C", birthDate: "" }, { id: 7598, firstName: "Mitch", lastName: "Eliot", jerseyNumber: 52, position: "D", birthDate: "" }] },
      { game_goal_id: "103643", team: { id: 390, name: "Utica Comets", city: "Utica", nickname: "Comets", abbreviation: "UTI", logo: "https://assets.leaguestat.com/ahl/logos/390.jpg", divisionName: "North Division" }, period: { id: "2", shortName: "", longName: "2nd" }, time: "5:41", scorerGoalNumber: "5", scoredBy: { id: 7287, firstName: "Jonah", lastName: "Gadjovich", jerseyNumber: 21, position: "F", birthDate: "" }, assists: [{ id: 7416, firstName: "Olli", lastName: "Juolevi", jerseyNumber: 48, position: "D", birthDate: "" }, { id: 4632, firstName: "Sven", lastName: "Baertschi", jerseyNumber: 47, position: "LW", birthDate: "" }], assistNumbers: %w[6 11], properties: { isPowerPlay: "1", isShortHanded: "0", isEmptyNet: "0", isPenaltyShot: "0", isInsuranceGoal: "0", isGameWinningGoal: "0" }, plus_players: [{ id: 7101, firstName: "Kole", lastName: "Lind", jerseyNumber: 13, position: "RW", birthDate: "" }, { id: 7287, firstName: "Jonah", lastName: "Gadjovich", jerseyNumber: 21, position: "F", birthDate: "" }, { id: 4552, firstName: "Reid", lastName: "Boucher", jerseyNumber: 24, position: "LW", birthDate: "" }, { id: 4632, firstName: "Sven", lastName: "Baertschi", jerseyNumber: 47, position: "LW", birthDate: "" }, { id: 7416, firstName: "Olli", lastName: "Juolevi", jerseyNumber: 48, position: "D", birthDate: "" }], minus_players: [{ id: 4889, firstName: "Seth", lastName: "Helgeson", jerseyNumber: 2, position: "D", birthDate: "" }, { id: 2050, firstName: "Colin", lastName: "McDonald", jerseyNumber: 13, position: "RW", birthDate: "" }, { id: 134, firstName: "Andrew", lastName: "Ladd", jerseyNumber: 16, position: "LW", birthDate: "" }, { id: 6241, firstName: "Parker", lastName: "Wotherspoon", jerseyNumber: 27, position: "D", birthDate: "" }] },
      { game_goal_id: "103650", team: { id: 317, name: "Bridgeport Sound Tigers", city: "Bridgeport", nickname: "Sound Tigers", abbreviation: "BRI", logo: "https://assets.leaguestat.com/ahl/logos/317.jpg", divisionName: "Atlantic Division" }, period: { id: "2", shortName: "", longName: "2nd" }, time: "12:15", scorerGoalNumber: "2", scoredBy: { id: 7538, firstName: "Grant", lastName: "Hutton", jerseyNumber: 7, position: "D", birthDate: "" }, assists: [{ id: 7646, firstName: "Mason", lastName: "Jobst", jerseyNumber: 25, position: "C", birthDate: "" }, { id: 6845, firstName: "Sebastian", lastName: "Aho", jerseyNumber: 28, position: "D", birthDate: "" }], assistNumbers: %w[4 11], properties: { isPowerPlay: "0", isShortHanded: "0", isEmptyNet: "0", isPenaltyShot: "0", isInsuranceGoal: "0", isGameWinningGoal: "0" }, plus_players: [{ id: 7538, firstName: "Grant", lastName: "Hutton", jerseyNumber: 7, position: "D", birthDate: "" }, { id: 6830, firstName: "Nick", lastName: "Schilkey", jerseyNumber: 17, position: "RW", birthDate: "" }, { id: 7646, firstName: "Mason", lastName: "Jobst", jerseyNumber: 25, position: "C", birthDate: "" }, { id: 6845, firstName: "Sebastian", lastName: "Aho", jerseyNumber: 28, position: "D", birthDate: "" }, { id: 4696, firstName: "Tom", lastName: "Kuhnhackl", jerseyNumber: 41, position: "RW", birthDate: "" }], minus_players: [{ id: 5929, firstName: "Ashton", lastName: "Sautner", jerseyNumber: 6, position: "D", birthDate: "" }, { id: 7516, firstName: "Seamus", lastName: "Malone", jerseyNumber: 17, position: "F", birthDate: "" }, { id: 4552, firstName: "Reid", lastName: "Boucher", jerseyNumber: 24, position: "LW", birthDate: "" }, { id: 4632, firstName: "Sven", lastName: "Baertschi", jerseyNumber: 47, position: "LW", birthDate: "" }, { id: 7416, firstName: "Olli", lastName: "Juolevi", jerseyNumber: 48, position: "D", birthDate: "" }] },
      { game_goal_id: "103660", team: { id: 390, name: "Utica Comets", city: "Utica", nickname: "Comets", abbreviation: "UTI", logo: "https://assets.leaguestat.com/ahl/logos/390.jpg", divisionName: "North Division" }, period: { id: "2", shortName: "", longName: "2nd" }, time: "19:08", scorerGoalNumber: "7", scoredBy: { id: 6080, firstName: "Justin", lastName: "Bailey", jerseyNumber: 95, position: "RW", birthDate: "" }, assists: [{ id: 4122, firstName: "Carter", lastName: "Camper", jerseyNumber: 19, position: "C", birthDate: "" }, { id: 7101, firstName: "Kole", lastName: "Lind", jerseyNumber: 13, position: "RW", birthDate: "" }], assistNumbers: %w[12 13], properties: { isPowerPlay: "0", isShortHanded: "0", isEmptyNet: "0", isPenaltyShot: "0", isInsuranceGoal: "0", isGameWinningGoal: "0" }, plus_players: [{ id: 7101, firstName: "Kole", lastName: "Lind", jerseyNumber: 13, position: "RW", birthDate: "" }, { id: 4122, firstName: "Carter", lastName: "Camper", jerseyNumber: 19, position: "C", birthDate: "" }, { id: 7893, firstName: "Brogan", lastName: "Rafferty", jerseyNumber: 25, position: "D", birthDate: "" }, { id: 6901, firstName: "Guillaume", lastName: "Brisebois", jerseyNumber: 55, position: "D", birthDate: "" }, { id: 6080, firstName: "Justin", lastName: "Bailey", jerseyNumber: 95, position: "RW", birthDate: "" }], minus_players: [{ id: 5478, firstName: "Kyle", lastName: "Burroughs", jerseyNumber: 8, position: "D", birthDate: "" }, { id: 6458, firstName: "Travis", lastName: "St. Denis", jerseyNumber: 24, position: "C", birthDate: "" }, { id: 7575, firstName: "Oliver", lastName: "Wahlstrom", jerseyNumber: 26, position: "RW", birthDate: "" }, { id: 6241, firstName: "Parker", lastName: "Wotherspoon", jerseyNumber: 27, position: "D", birthDate: "" }, { id: 4696, firstName: "Tom", lastName: "Kuhnhackl", jerseyNumber: 41, position: "RW", birthDate: "" }] },
      { game_goal_id: "103672", team: { id: 317, name: "Bridgeport Sound Tigers", city: "Bridgeport", nickname: "Sound Tigers", abbreviation: "BRI", logo: "https://assets.leaguestat.com/ahl/logos/317.jpg", divisionName: "Atlantic Division" }, period: { id: "3", shortName: "", longName: "3rd" }, time: "6:53", scorerGoalNumber: "4", scoredBy: { id: 7188, firstName: "Kieffer", lastName: "Bellows", jerseyNumber: 20, position: "LW", birthDate: "" }, assists: [{ id: 5834, firstName: "Matt", lastName: "Lorito", jerseyNumber: 14, position: "RW", birthDate: "" }, { id: 6845, firstName: "Sebastian", lastName: "Aho", jerseyNumber: 28, position: "D", birthDate: "" }], assistNumbers: %w[7 12], properties: { isPowerPlay: "0", isShortHanded: "0", isEmptyNet: "0", isPenaltyShot: "0", isInsuranceGoal: "0", isGameWinningGoal: "0" }, plus_players: [{ id: 5478, firstName: "Kyle", lastName: "Burroughs", jerseyNumber: 8, position: "D", birthDate: "" }, { id: 2050, firstName: "Colin", lastName: "McDonald", jerseyNumber: 13, position: "RW", birthDate: "" }, { id: 5834, firstName: "Matt", lastName: "Lorito", jerseyNumber: 14, position: "RW", birthDate: "" }, { id: 7188, firstName: "Kieffer", lastName: "Bellows", jerseyNumber: 20, position: "LW", birthDate: "" }, { id: 6241, firstName: "Parker", lastName: "Wotherspoon", jerseyNumber: 27, position: "D", birthDate: "" }], minus_players: [{ id: 6834, firstName: "Stefan", lastName: "LeBlanc", jerseyNumber: 3, position: "D", birthDate: "" }, { id: 7082, firstName: "Lukas", lastName: "Jasek", jerseyNumber: 9, position: "RW", birthDate: "" }, { id: 4552, firstName: "Reid", lastName: "Boucher", jerseyNumber: 24, position: "LW", birthDate: "" }, { id: 4632, firstName: "Sven", lastName: "Baertschi", jerseyNumber: 47, position: "LW", birthDate: "" }, { id: 6901, firstName: "Guillaume", lastName: "Brisebois", jerseyNumber: 55, position: "D", birthDate: "" }] },
      { game_goal_id: "103674", team: { id: 390, name: "Utica Comets", city: "Utica", nickname: "Comets", abbreviation: "UTI", logo: "https://assets.leaguestat.com/ahl/logos/390.jpg", divisionName: "North Division" }, period: { id: "3", shortName: "", longName: "3rd" }, time: "7:45", scorerGoalNumber: "16", scoredBy: { id: 4552, firstName: "Reid", lastName: "Boucher", jerseyNumber: 24, position: "LW", birthDate: "" }, assists: [{ id: 4632, firstName: "Sven", lastName: "Baertschi", jerseyNumber: 47, position: "LW", birthDate: "" }], assistNumbers: %w[12 0], properties: { isPowerPlay: "0", isShortHanded: "0", isEmptyNet: "0", isPenaltyShot: "0", isInsuranceGoal: "0", isGameWinningGoal: "0" }, plus_players: [{ id: 6834, firstName: "Stefan", lastName: "LeBlanc", jerseyNumber: 3, position: "D", birthDate: "" }, { id: 7082, firstName: "Lukas", lastName: "Jasek", jerseyNumber: 9, position: "RW", birthDate: "" }, { id: 4552, firstName: "Reid", lastName: "Boucher", jerseyNumber: 24, position: "LW", birthDate: "" }, { id: 4632, firstName: "Sven", lastName: "Baertschi", jerseyNumber: 47, position: "LW", birthDate: "" }, { id: 7598, firstName: "Mitch", lastName: "Eliot", jerseyNumber: 52, position: "D", birthDate: "" }], minus_players: [{ id: 134, firstName: "Andrew", lastName: "Ladd", jerseyNumber: 16, position: "LW", birthDate: "" }, { id: 6241, firstName: "Parker", lastName: "Wotherspoon", jerseyNumber: 27, position: "D", birthDate: "" }, { id: 7189, firstName: "Arnaud", lastName: "Durandeau", jerseyNumber: 29, position: "LW", birthDate: "" }, { id: 6748, firstName: "Jeff", lastName: "Kubiak", jerseyNumber: 36, position: "C", birthDate: "" }, { id: 7198, firstName: "Bode", lastName: "Wilde", jerseyNumber: 46, position: "D", birthDate: "" }] },
    ]
  end
  let(:shot_data) { [{ home: 8, away: 11 }, { home: 9, away: 11 }, { home: 9, away: 15 }, { home: 5, away: 3 }] }
  let(:current_state) { { status: "finished", time: nil, period: nil, period_number: nil, overtime: true, shootout: true } }
  let(:is_home_team) { true }

  it "converts raw data into attributes" do
    team = described_class.new(raw_data, opts)

    expect(team.id).to eq(raw_data[:info][:id])
    expect(team.full_name).to eq(raw_data[:info][:name])
    expect(team.city).to eq(raw_data[:info][:city])
    expect(team.name).to eq(raw_data[:info][:nickname])
    expect(team.abbreviation).to eq(raw_data[:info][:abbreviation])
    expect(team.logo_url).to eq(raw_data[:info][:logo])
    expect(team.stats[:score]).to eq(raw_data[:stats][:goals])
    expect(team.stats[:hits]).to eq(raw_data[:stats][:hits])
    expect(team.stats[:power_play_goals]).to eq(raw_data[:stats][:powerPlayGoals])
    expect(team.stats[:power_play_opportunities]).to eq(raw_data[:stats][:powerPlayOpportunities])
    expect(team.stats[:goals]).to eq(raw_data[:stats][:goalCount])
    expect(team.stats[:assist_count]).to eq(raw_data[:stats][:assisCount])
    expect(team.stats[:penalty_minute_count]).to eq(raw_data[:stats][:penaltyMinuteCount])
    expect(team.stats[:infraction_count]).to eq(raw_data[:stats][:infractionCount])
    expect(team.shot_stats[:sog]).to eq(31)
    expect(team.shot_stats[:p1_sog]).to eq(8)
    expect(team.shot_stats[:p2_sog]).to eq(9)
    expect(team.shot_stats[:p3_sog]).to eq(9)
    expect(team.shot_stats[:ot_sog]).to match_array([5])
  end

  context "when away team" do
    let(:is_home_team) { false }

    it "sets home_team? to false" do
      team = described_class.new(raw_data, opts)

      expect(team.home_team?).to eq(false)
    end
  end

  context "when home team" do
    let(:is_home_team) { true }

    it "sets home_team? to true" do
      team = described_class.new(raw_data, { home_team: true })

      expect(team.home_team?).to eq(true)
    end
  end
end
